services:
  fast_api:
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: ubuntu
        USER_GID: 1000
        USER_UID: 1000
        BUILD_VERSION: DEV
        WORKDIR: /Projects/fast_api
    platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/Projects:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 