include:
  - backend_dotnet/docker-compose.yml
  - fast_api/docker-compose.yml

services:
  mongo:
    image: mongo:8.0.13
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: